service: cart-api

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    PG_HOST: nuts-store-db.cubrk7lcy2dg.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DB_NAME: nutsstore
    PG_USERNAME: postgres

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
